apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: openshift-migrationproxy
    name: openshift-migrationproxy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-migrationproxy:latest
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/ure/openshift-migrationproxy.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:7
      type: Docker
  status:
    lastVersion: 0
kind: List
metadata: {}
